### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tugsi** [iobroker-community-adapters/ioBroker.tvspielfilm#34]
Got some Errormessages in the Log:

`

tvspielfilm.0 |  error | Cannot read property 'length' of undefined
-- | -- | -- | --
tvspielfilm.0 |  error | TypeError: Cannot read property 'length' of undefined at /opt/iobroker/node_modules/iobroker.tvspielfilm/main.js:191:49 at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:304:18) at Parser.emit (events.js:400:28) at SAXParser.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:262:26) at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35) at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5) at closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/opt/iobroker/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/opt/iobroker/node_modules/xml2js/lib/parser.js:323:31) at Parser.parseString (/opt/iobroker/node_modules/xml2js/lib/parser.js:5:59)
tvspielfilm.0 |  error | uncaught exception: Cannot read property 'length' of undefined
tvspielfilm.0 |  info | objects written

`
Nothing changed before, not the only one with this Problems:
[https://forum.iobroker.net/topic/60675/fehler-bei-adapter-tvspielfilm](https://forum.iobroker.net/topic/60675/fehler-bei-adapter-tvspielfilm)

**Comment by tugsi** [comment]
@Apollon77

**Comment by Pix---** [comment]
On tvspielfilm's website the feed "Filme" is listed.
https://www.tvspielfilm.de/tv-programm/rss/filme.xml

Probably a good alternative to tv_tipps.

**Comment by Apollon77** [comment]
@Pix--- Do you want to make a PR or even directly change it?

**Comment by Pix---** [comment]
@Apollon77 Just noticed *filme* is in the code already. So merging @tugsi PR would be the best by now.

**Comment by Apollon77** [comment]
Can someone please try GitHub version before I release it to verify? Thanks you for your feedback

**Comment by Apollon77** [comment]
Added again an additional check. Any test would be awwsome

**Comment by tugsi** [comment]
@Apollon77 
Tested on two Systems... everything fine, no problems or Issues 
For me, you can make a release.
Thanks

**Comment by Apollon77** [comment]
v2.0.5 on its way. Thank you
